namespace DataAcquisitionService
{
	partial class DSNPerformanceForm
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			dotnetCHARTING.WinForms.ChartArea chartArea1 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background1 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element1 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue1 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line1 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot1 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry1 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background2 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line2 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot2 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line3 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label1 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation1 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendBox legendBox1 = new dotnetCHARTING.WinForms.LegendBox();
			dotnetCHARTING.WinForms.Background background3 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.LegendEntry legendEntry2 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background4 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line4 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot3 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Label label2 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation2 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendEntry legendEntry3 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background5 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line5 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot4 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line6 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line7 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow1 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Line line8 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow2 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box1 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background6 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line9 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label3 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation3 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line10 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow3 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Axis axis1 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick1 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line11 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line12 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick2 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line13 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line14 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange1 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line15 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick3 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line16 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line17 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Axis axis2 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick4 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line18 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line19 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick5 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line20 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line21 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange2 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line22 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick6 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line23 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line24 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Axis axis3 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick7 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line25 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line26 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange3 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line27 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick8 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line28 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line29 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Element element2 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue2 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line30 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot5 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry4 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background7 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line31 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot6 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.SmartLabel smartLabel1 = new dotnetCHARTING.WinForms.SmartLabel();
			dotnetCHARTING.WinForms.Line line32 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Truncation truncation4 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Shadow shadow4 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Truncation truncation5 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.ChartArea chartArea2 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background8 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element3 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue3 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line33 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot7 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry5 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background9 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line34 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot8 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line35 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label4 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation6 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line36 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow5 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box2 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background10 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line37 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label5 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation7 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line38 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow6 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.ChartArea chartArea3 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background11 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element4 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue4 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line39 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot9 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry6 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background12 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line40 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot10 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line41 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label6 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation8 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendBox legendBox2 = new dotnetCHARTING.WinForms.LegendBox();
			dotnetCHARTING.WinForms.Background background13 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.LegendEntry legendEntry7 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background14 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line42 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot11 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Label label7 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation9 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendEntry legendEntry8 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background15 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line43 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot12 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line44 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line45 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow7 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Line line46 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow8 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box3 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background16 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line47 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label8 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation10 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line48 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow9 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Axis axis4 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick9 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line49 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line50 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick10 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line51 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line52 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange4 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line53 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick11 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line54 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line55 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Axis axis5 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick12 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line56 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line57 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick13 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line58 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line59 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange5 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line60 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick14 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line61 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line62 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Axis axis6 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick15 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line63 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line64 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange6 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line65 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick16 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line66 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line67 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Element element5 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue5 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line68 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot13 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry9 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background17 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line69 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot14 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.SmartLabel smartLabel2 = new dotnetCHARTING.WinForms.SmartLabel();
			dotnetCHARTING.WinForms.Line line70 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Truncation truncation11 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Shadow shadow10 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Truncation truncation12 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.ChartArea chartArea4 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background18 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element6 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue6 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line71 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot15 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry10 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background19 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line72 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot16 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line73 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label9 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation13 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line74 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow11 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box4 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background20 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line75 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label10 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation14 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line76 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow12 = new dotnetCHARTING.WinForms.Shadow();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DSNPerformanceForm));
			dotnetCHARTING.WinForms.ChartArea chartArea5 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background21 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element7 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue7 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line77 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot17 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry11 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background22 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line78 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot18 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line79 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label11 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation15 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendBox legendBox3 = new dotnetCHARTING.WinForms.LegendBox();
			dotnetCHARTING.WinForms.Background background23 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.LegendEntry legendEntry12 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background24 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line80 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot19 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Label label12 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation16 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendEntry legendEntry13 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background25 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line81 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot20 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line82 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line83 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow13 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Line line84 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow14 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box5 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background26 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line85 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label13 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation17 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line86 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow15 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Axis axis7 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick17 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line87 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line88 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange7 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line89 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick18 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line90 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line91 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Element element8 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue8 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line92 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot21 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry14 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background27 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line93 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot22 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.SmartLabel smartLabel3 = new dotnetCHARTING.WinForms.SmartLabel();
			dotnetCHARTING.WinForms.Line line94 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Truncation truncation18 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Shadow shadow16 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Truncation truncation19 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.ChartArea chartArea6 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background28 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element9 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue9 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line95 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot23 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry15 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background29 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line96 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot24 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line97 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label14 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation20 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line98 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow17 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box6 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background30 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line99 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label15 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation21 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line100 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow18 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.ChartArea chartArea7 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background31 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element10 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue10 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line101 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot25 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry16 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background32 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line102 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot26 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line103 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label16 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation22 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendBox legendBox4 = new dotnetCHARTING.WinForms.LegendBox();
			dotnetCHARTING.WinForms.Background background33 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.LegendEntry legendEntry17 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background34 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line104 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot27 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Label label17 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation23 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.LegendEntry legendEntry18 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background35 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line105 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot28 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line106 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line107 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow19 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Line line108 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow20 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box7 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background36 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line109 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label18 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation24 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line110 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow21 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Axis axis8 = new dotnetCHARTING.WinForms.Axis();
			dotnetCHARTING.WinForms.AxisTick axisTick19 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line111 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line112 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.ScaleRange scaleRange8 = new dotnetCHARTING.WinForms.ScaleRange();
			dotnetCHARTING.WinForms.Line line113 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.AxisTick axisTick20 = new dotnetCHARTING.WinForms.AxisTick();
			dotnetCHARTING.WinForms.Line line114 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Line line115 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Element element11 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue11 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line116 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot29 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry19 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background37 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line117 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot30 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.SmartLabel smartLabel4 = new dotnetCHARTING.WinForms.SmartLabel();
			dotnetCHARTING.WinForms.Line line118 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Truncation truncation25 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Shadow shadow22 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Truncation truncation26 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.ChartArea chartArea8 = new dotnetCHARTING.WinForms.ChartArea();
			dotnetCHARTING.WinForms.Background background38 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Element element12 = new dotnetCHARTING.WinForms.Element();
			dotnetCHARTING.WinForms.SubValue subValue12 = new dotnetCHARTING.WinForms.SubValue();
			dotnetCHARTING.WinForms.Line line119 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot31 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.LegendEntry legendEntry20 = new dotnetCHARTING.WinForms.LegendEntry();
			dotnetCHARTING.WinForms.Background background39 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line120 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Hotspot hotspot32 = new dotnetCHARTING.WinForms.Hotspot();
			dotnetCHARTING.WinForms.Line line121 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label19 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation27 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line122 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow23 = new dotnetCHARTING.WinForms.Shadow();
			dotnetCHARTING.WinForms.Box box8 = new dotnetCHARTING.WinForms.Box();
			dotnetCHARTING.WinForms.Background background40 = new dotnetCHARTING.WinForms.Background();
			dotnetCHARTING.WinForms.Line line123 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Label label20 = new dotnetCHARTING.WinForms.Label();
			dotnetCHARTING.WinForms.Truncation truncation28 = new dotnetCHARTING.WinForms.Truncation();
			dotnetCHARTING.WinForms.Line line124 = new dotnetCHARTING.WinForms.Line();
			dotnetCHARTING.WinForms.Shadow shadow24 = new dotnetCHARTING.WinForms.Shadow();
			this.gbPrecision = new System.Windows.Forms.GroupBox();
			this.chartPrecision = new dotnetCHARTING.WinForms.Chart();
			this.gbActiveSensors = new System.Windows.Forms.GroupBox();
			this.chartActiveSensors = new dotnetCHARTING.WinForms.Chart();
			this.gbNetwork = new System.Windows.Forms.GroupBox();
			this.SensorTopView = new System.Windows.Forms.PictureBox();
			this.buttonDemo = new System.Windows.Forms.Button();
			this.buttonClose = new System.Windows.Forms.Button();
			this.tcCharts = new System.Windows.Forms.TabControl();
			this.tabPageData = new System.Windows.Forms.TabPage();
			this.tabPagePerformance = new System.Windows.Forms.TabPage();
			this.buttonReset = new System.Windows.Forms.Button();
			this.button1 = new System.Windows.Forms.Button();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.chartCumulative = new dotnetCHARTING.WinForms.Chart();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.chartGauges = new dotnetCHARTING.WinForms.Chart();
			this.buttonClear = new System.Windows.Forms.Button();
			this.gbPrecision.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartPrecision)).BeginInit();
			this.gbActiveSensors.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartActiveSensors)).BeginInit();
			this.gbNetwork.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.SensorTopView)).BeginInit();
			this.tcCharts.SuspendLayout();
			this.tabPageData.SuspendLayout();
			this.tabPagePerformance.SuspendLayout();
			this.groupBox2.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartCumulative)).BeginInit();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.chartGauges)).BeginInit();
			this.SuspendLayout();
			// 
			// gbPrecision
			// 
			this.gbPrecision.Controls.Add(this.chartPrecision);
			this.gbPrecision.Location = new System.Drawing.Point(3, 6);
			this.gbPrecision.Name = "gbPrecision";
			this.gbPrecision.Size = new System.Drawing.Size(430, 263);
			this.gbPrecision.TabIndex = 0;
			this.gbPrecision.TabStop = false;
			this.gbPrecision.Text = "Estimation Error";
			// 
			// chartPrecision
			// 
			this.chartPrecision.Application = "ZVZ5uFmhG+9VZZ4UL7KCqlEt5AKQhFYbFKcmePBaLW17Nt2xzFTAVlZDJwElG5tq46yOLrS+6Ydf1lCvU" +
				"TpGlw==";
            //this.chartPrecision.ApplicationDNC = "ZVZ5uFmhG+9VZZ4UL7KCqlEt5AKQhFYbFKcmePBaLW17Nt2xzFTAVlZDJwElG5tq46yOLrS+6Ydf1lCvU" +
            //    "TpGlw==";
			this.chartPrecision.Background.Color = System.Drawing.Color.White;
			background1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea1.Background = background1;
			line1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			line1.Length = 4;
			subValue1.Line = line1;
			element1.DefaultSubValue = subValue1;
			element1.Hotspot = hotspot1;
			legendEntry1.Background = background2;
			line2.Color = System.Drawing.Color.Empty;
			legendEntry1.DividerLine = line2;
			legendEntry1.Hotspot = hotspot2;
			element1.LegendEntry = legendEntry1;
			element1.XAxisTick = null;
			element1.YAxisTick = null;
			chartArea1.DefaultElement = element1;
			line3.Color = System.Drawing.Color.LightGray;
			chartArea1.InteriorLine = line3;
			label1.Font = new System.Drawing.Font("Tahoma", 8F);
			label1.Truncation = truncation1;
			chartArea1.Label = label1;
			background3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			legendBox1.Background = background3;
			legendBox1.CornerBottomRight = dotnetCHARTING.WinForms.BoxCorner.Cut;
			legendEntry2.Background = background4;
			line4.Color = System.Drawing.Color.Empty;
			legendEntry2.DividerLine = line4;
			legendEntry2.Hotspot = hotspot3;
			label2.Truncation = truncation2;
			legendEntry2.LabelStyle = label2;
			legendBox1.DefaultEntry = legendEntry2;
			legendEntry3.Background = background5;
			line5.Color = System.Drawing.Color.Gray;
			legendEntry3.DividerLine = line5;
			legendEntry3.Hotspot = hotspot4;
			legendEntry3.Name = "Name";
			legendEntry3.SortOrder = -1;
			legendEntry3.Value = "Value";
			legendEntry3.Visible = false;
			legendBox1.HeaderEntry = legendEntry3;
			line6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			legendBox1.InteriorLine = line6;
			legendBox1.LabelStyle = label2;
			line7.Color = System.Drawing.Color.Gray;
			legendBox1.Line = line7;
			legendBox1.Padding = 4;
			legendBox1.Shadow = shadow1;
			legendBox1.Visible = true;
			chartArea1.LegendBox = legendBox1;
			line8.Color = System.Drawing.Color.Gray;
			chartArea1.Line = line8;
			chartArea1.Shadow = shadow2;
			chartArea1.StartDateOfYear = new System.DateTime(((long)(0)));
			background6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box1.Background = background6;
			line9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box1.InteriorLine = line9;
			label3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label3.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label3.Truncation = truncation3;
			box1.Label = label3;
			line10.Color = System.Drawing.Color.Gray;
			box1.Line = line10;
			box1.Position = dotnetCHARTING.WinForms.TitleBoxPosition.Left;
			box1.Shadow = shadow3;
			box1.Visible = true;
			chartArea1.TitleBox = box1;
			axis1.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			line11.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;
			axisTick1.GridLine = line11;
			line12.Color = System.Drawing.Color.Gray;
			line12.Length = 2;
			axisTick1.Line = line12;
			axisTick1.ValueLow = double.NaN;
			axis1.DefaultMinorTick = axisTick1;
			line13.Color = System.Drawing.Color.LightGray;
			axisTick2.GridLine = line13;
			line14.Length = 3;
			axisTick2.Line = line14;
			axisTick2.ValueLow = double.NaN;
			axis1.DefaultTick = axisTick2;
			axis1.LabelMarker = null;
			axis1.LogarithmicBase = 10;
			axis1.OverlappingCircularLabelSeparator = " & ";
			axis1.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis1.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange1.ValueLow = double.NaN;
			axis1.ScaleRange = scaleRange1;
			axis1.TickLabelAngle = 45F;
			axis1.TickLabelSeparatorLine = line15;
			line16.Color = System.Drawing.Color.Red;
			axisTick3.GridLine = line16;
			line17.Length = 3;
			axisTick3.Line = line17;
			axisTick3.Value = 0;
			axisTick3.ValueHigh = 0;
			axisTick3.ValueLow = 0;
			axis1.ZeroTick = axisTick3;
			chartArea1.XAxis = axis1;
			axis2.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			line18.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;
			axisTick4.GridLine = line18;
			line19.Color = System.Drawing.Color.Gray;
			line19.Length = 2;
			axisTick4.Line = line19;
			axisTick4.ValueLow = double.NaN;
			axis2.DefaultMinorTick = axisTick4;
			line20.Color = System.Drawing.Color.LightGray;
			axisTick5.GridLine = line20;
			line21.Length = 3;
			axisTick5.Line = line21;
			axisTick5.ValueLow = double.NaN;
			axis2.DefaultTick = axisTick5;
			axis2.LabelMarker = null;
			axis2.LogarithmicBase = 10;
			axis2.OverlappingCircularLabelSeparator = " & ";
			axis2.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis2.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange2.ValueLow = double.NaN;
			axis2.ScaleRange = scaleRange2;
			axis2.TickLabelAngle = 45F;
			axis2.TickLabelSeparatorLine = line22;
			line23.Color = System.Drawing.Color.Red;
			axisTick6.GridLine = line23;
			line24.Length = 3;
			axisTick6.Line = line24;
			axisTick6.Value = 0;
			axisTick6.ValueHigh = 0;
			axisTick6.ValueLow = 0;
			axis2.ZeroTick = axisTick6;
			chartArea1.YAxis = axis2;
			this.chartPrecision.ChartArea = chartArea1;
			this.chartPrecision.DataGrid = null;
			axis3.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line25.Color = System.Drawing.Color.LightGray;
			axisTick7.GridLine = line25;
			line26.Length = 3;
			axisTick7.Line = line26;
			axisTick7.ValueLow = double.NaN;
			axis3.DefaultTick = axisTick7;
			axis3.LabelMarker = null;
			axis3.LogarithmicBase = 10;
			axis3.OverlappingCircularLabelSeparator = " & ";
			axis3.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis3.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange3.ValueLow = double.NaN;
			axis3.ScaleRange = scaleRange3;
			axis3.TickLabelAngle = 45F;
			axis3.TickLabelSeparatorLine = line27;
			line28.Color = System.Drawing.Color.Red;
			axisTick8.GridLine = line28;
			line29.Length = 3;
			axisTick8.Line = line29;
			axisTick8.ValueLow = double.NaN;
			axis3.ZeroTick = axisTick8;
			this.chartPrecision.DefaultAxis = axis3;
			this.chartPrecision.DefaultCultureName = "";
			line30.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			line30.Length = 4;
			subValue2.Line = line30;
			element2.DefaultSubValue = subValue2;
			element2.Hotspot = hotspot5;
			legendEntry4.Background = background7;
			line31.Color = System.Drawing.Color.Empty;
			legendEntry4.DividerLine = line31;
			legendEntry4.Hotspot = hotspot6;
			element2.LegendEntry = legendEntry4;
			smartLabel1.Color = System.Drawing.Color.Empty;
			line32.Color = System.Drawing.Color.Transparent;
			smartLabel1.Line = line32;
			smartLabel1.Truncation = truncation4;
			element2.SmartLabel = smartLabel1;
			element2.XAxisTick = null;
			element2.YAxisTick = null;
			this.chartPrecision.DefaultElement = element2;
			this.chartPrecision.DefaultShadow = shadow4;
			this.chartPrecision.Dock = System.Windows.Forms.DockStyle.Fill;
			this.chartPrecision.Location = new System.Drawing.Point(3, 16);
			this.chartPrecision.Name = "chartPrecision";
			this.chartPrecision.NoDataLabel.Text = "No Data";
			this.chartPrecision.NoDataLabel.Truncation = truncation5;
			this.chartPrecision.Size = new System.Drawing.Size(424, 244);
			this.chartPrecision.SmartLabelLine = line32;
			this.chartPrecision.SmartPaletteAutoSync = false;
			this.chartPrecision.StartDateOfYear = new System.DateTime(((long)(0)));
			this.chartPrecision.TabIndex = 0;
			this.chartPrecision.TempDirectory = "C:\\Documents and Settings\\ntas\\Local Settings\\Temp\\";
			this.chartPrecision.ToolTipTemplate = "";
			this.chartPrecision.Type = dotnetCHARTING.WinForms.ChartType.Scatter;
			background8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea2.Background = background8;
			line33.Length = 4;
			subValue3.Line = line33;
			element3.DefaultSubValue = subValue3;
			element3.Hotspot = hotspot7;
			legendEntry5.Background = background9;
			line34.Color = System.Drawing.Color.Empty;
			legendEntry5.DividerLine = line34;
			legendEntry5.Hotspot = hotspot8;
			element3.LegendEntry = legendEntry5;
			element3.XAxisTick = null;
			element3.YAxisTick = null;
			chartArea2.DefaultElement = element3;
			line35.Color = System.Drawing.Color.LightGray;
			chartArea2.InteriorLine = line35;
			label4.Font = new System.Drawing.Font("Tahoma", 8F);
			label4.Truncation = truncation6;
			chartArea2.Label = label4;
			chartArea2.LegendBox = null;
			line36.Color = System.Drawing.Color.Gray;
			chartArea2.Line = line36;
			chartArea2.Shadow = shadow5;
			chartArea2.StartDateOfYear = new System.DateTime(((long)(0)));
			background10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box2.Background = background10;
			line37.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box2.InteriorLine = line37;
			label5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label5.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label5.Truncation = truncation7;
			box2.Label = label5;
			line38.Color = System.Drawing.Color.Gray;
			box2.Line = line38;
			box2.Shadow = shadow6;
			box2.Visible = true;
			chartArea2.TitleBox = box2;
			chartArea2.XAxis = axis1;
			this.chartPrecision.VolumeArea = chartArea2;
			// 
			// gbActiveSensors
			// 
			this.gbActiveSensors.Controls.Add(this.chartActiveSensors);
			this.gbActiveSensors.Location = new System.Drawing.Point(433, 6);
			this.gbActiveSensors.Name = "gbActiveSensors";
			this.gbActiveSensors.Size = new System.Drawing.Size(422, 263);
			this.gbActiveSensors.TabIndex = 1;
			this.gbActiveSensors.TabStop = false;
			this.gbActiveSensors.Text = "Number of Active Sensors";
			// 
			// chartActiveSensors
			// 
			this.chartActiveSensors.Application = "ZVZ5uFmhG+9VZZ4UL7KCqlEt5AKQhFYbFKcmePBaLW17Nt2xzFTAVlZDJwElG5tq46yOLrS+6Ydf1lCvU" +
				"TpGlw==";
            //this.chartActiveSensors.ApplicationDNC = "ZVZ5uFmhG+9VZZ4UL7KCqlEt5AKQhFYbFKcmePBaLW17Nt2xzFTAVlZDJwElG5tq46yOLrS+6Ydf1lCvU" +
            //    "TpGlw==";
			this.chartActiveSensors.Background.Color = System.Drawing.Color.White;
			background11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea3.Background = background11;
			line39.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			line39.Length = 4;
			subValue4.Line = line39;
			element4.DefaultSubValue = subValue4;
			element4.Hotspot = hotspot9;
			legendEntry6.Background = background12;
			line40.Color = System.Drawing.Color.Empty;
			legendEntry6.DividerLine = line40;
			legendEntry6.Hotspot = hotspot10;
			element4.LegendEntry = legendEntry6;
			element4.XAxisTick = null;
			element4.YAxisTick = null;
			chartArea3.DefaultElement = element4;
			line41.Color = System.Drawing.Color.LightGray;
			chartArea3.InteriorLine = line41;
			label6.Font = new System.Drawing.Font("Tahoma", 8F);
			label6.Truncation = truncation8;
			chartArea3.Label = label6;
			background13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			legendBox2.Background = background13;
			legendBox2.CornerBottomRight = dotnetCHARTING.WinForms.BoxCorner.Cut;
			legendEntry7.Background = background14;
			line42.Color = System.Drawing.Color.Empty;
			legendEntry7.DividerLine = line42;
			legendEntry7.Hotspot = hotspot11;
			label7.Truncation = truncation9;
			legendEntry7.LabelStyle = label7;
			legendBox2.DefaultEntry = legendEntry7;
			legendEntry8.Background = background15;
			line43.Color = System.Drawing.Color.Gray;
			legendEntry8.DividerLine = line43;
			legendEntry8.Hotspot = hotspot12;
			legendEntry8.Name = "Name";
			legendEntry8.SortOrder = -1;
			legendEntry8.Value = "Value";
			legendEntry8.Visible = false;
			legendBox2.HeaderEntry = legendEntry8;
			line44.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			legendBox2.InteriorLine = line44;
			legendBox2.LabelStyle = label7;
			line45.Color = System.Drawing.Color.Gray;
			legendBox2.Line = line45;
			legendBox2.Padding = 4;
			legendBox2.Shadow = shadow7;
			legendBox2.Visible = true;
			chartArea3.LegendBox = legendBox2;
			line46.Color = System.Drawing.Color.Gray;
			chartArea3.Line = line46;
			chartArea3.Shadow = shadow8;
			chartArea3.StartDateOfYear = new System.DateTime(((long)(0)));
			background16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box3.Background = background16;
			line47.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box3.InteriorLine = line47;
			label8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label8.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label8.Truncation = truncation10;
			box3.Label = label8;
			line48.Color = System.Drawing.Color.Gray;
			box3.Line = line48;
			box3.Position = dotnetCHARTING.WinForms.TitleBoxPosition.Left;
			box3.Shadow = shadow9;
			box3.Visible = true;
			chartArea3.TitleBox = box3;
			axis4.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line49.Color = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			line49.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;
			axisTick9.GridLine = line49;
			line50.Color = System.Drawing.Color.Gray;
			line50.Length = 2;
			axisTick9.Line = line50;
			axisTick9.ValueLow = double.NaN;
			axis4.DefaultMinorTick = axisTick9;
			line51.Color = System.Drawing.Color.LightGray;
			axisTick10.GridLine = line51;
			line52.Length = 3;
			axisTick10.Line = line52;
			axisTick10.ValueLow = double.NaN;
			axis4.DefaultTick = axisTick10;
			axis4.LabelMarker = null;
			axis4.LogarithmicBase = 10;
			axis4.OverlappingCircularLabelSeparator = " & ";
			axis4.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis4.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange4.ValueLow = double.NaN;
			axis4.ScaleRange = scaleRange4;
			axis4.TickLabelAngle = 45F;
			axis4.TickLabelSeparatorLine = line53;
			line54.Color = System.Drawing.Color.Red;
			axisTick11.GridLine = line54;
			line55.Length = 3;
			axisTick11.Line = line55;
			axisTick11.Value = 0;
			axisTick11.ValueHigh = 0;
			axisTick11.ValueLow = 0;
			axis4.ZeroTick = axisTick11;
			chartArea3.XAxis = axis4;
			axis5.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line56.Color = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
			line56.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;
			axisTick12.GridLine = line56;
			line57.Color = System.Drawing.Color.Gray;
			line57.Length = 2;
			axisTick12.Line = line57;
			axisTick12.ValueLow = double.NaN;
			axis5.DefaultMinorTick = axisTick12;
			line58.Color = System.Drawing.Color.LightGray;
			axisTick13.GridLine = line58;
			line59.Length = 3;
			axisTick13.Line = line59;
			axisTick13.ValueLow = double.NaN;
			axis5.DefaultTick = axisTick13;
			axis5.LabelMarker = null;
			axis5.LogarithmicBase = 10;
			axis5.OverlappingCircularLabelSeparator = " & ";
			axis5.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis5.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange5.ValueLow = double.NaN;
			axis5.ScaleRange = scaleRange5;
			axis5.TickLabelAngle = 45F;
			axis5.TickLabelSeparatorLine = line60;
			line61.Color = System.Drawing.Color.Red;
			axisTick14.GridLine = line61;
			line62.Length = 3;
			axisTick14.Line = line62;
			axisTick14.Value = 0;
			axisTick14.ValueHigh = 0;
			axisTick14.ValueLow = 0;
			axis5.ZeroTick = axisTick14;
			chartArea3.YAxis = axis5;
			this.chartActiveSensors.ChartArea = chartArea3;
			this.chartActiveSensors.DataGrid = null;
			axis6.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line63.Color = System.Drawing.Color.LightGray;
			axisTick15.GridLine = line63;
			line64.Length = 3;
			axisTick15.Line = line64;
			axisTick15.ValueLow = double.NaN;
			axis6.DefaultTick = axisTick15;
			axis6.LabelMarker = null;
			axis6.LogarithmicBase = 10;
			axis6.OverlappingCircularLabelSeparator = " & ";
			axis6.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis6.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange6.ValueLow = double.NaN;
			axis6.ScaleRange = scaleRange6;
			axis6.TickLabelAngle = 45F;
			axis6.TickLabelSeparatorLine = line65;
			line66.Color = System.Drawing.Color.Red;
			axisTick16.GridLine = line66;
			line67.Length = 3;
			axisTick16.Line = line67;
			axisTick16.ValueLow = double.NaN;
			axis6.ZeroTick = axisTick16;
			this.chartActiveSensors.DefaultAxis = axis6;
			this.chartActiveSensors.DefaultCultureName = "";
			line68.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			line68.Length = 4;
			subValue5.Line = line68;
			element5.DefaultSubValue = subValue5;
			element5.Hotspot = hotspot13;
			legendEntry9.Background = background17;
			line69.Color = System.Drawing.Color.Empty;
			legendEntry9.DividerLine = line69;
			legendEntry9.Hotspot = hotspot14;
			element5.LegendEntry = legendEntry9;
			smartLabel2.Color = System.Drawing.Color.Empty;
			line70.Color = System.Drawing.Color.Transparent;
			smartLabel2.Line = line70;
			smartLabel2.Truncation = truncation11;
			element5.SmartLabel = smartLabel2;
			element5.XAxisTick = null;
			element5.YAxisTick = null;
			this.chartActiveSensors.DefaultElement = element5;
			this.chartActiveSensors.DefaultShadow = shadow10;
			this.chartActiveSensors.Dock = System.Windows.Forms.DockStyle.Fill;
			this.chartActiveSensors.Location = new System.Drawing.Point(3, 16);
			this.chartActiveSensors.Name = "chartActiveSensors";
			this.chartActiveSensors.NoDataLabel.Text = "No Data";
			this.chartActiveSensors.NoDataLabel.Truncation = truncation12;
			this.chartActiveSensors.Size = new System.Drawing.Size(416, 244);
			this.chartActiveSensors.SmartLabelLine = line70;
			this.chartActiveSensors.SmartPaletteAutoSync = false;
			this.chartActiveSensors.StartDateOfYear = new System.DateTime(((long)(0)));
			this.chartActiveSensors.TabIndex = 1;
			this.chartActiveSensors.TempDirectory = "C:\\Documents and Settings\\ntas\\Local Settings\\Temp\\";
			this.chartActiveSensors.ToolTipTemplate = "";
			this.chartActiveSensors.Type = dotnetCHARTING.WinForms.ChartType.Scatter;
			background18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea4.Background = background18;
			line71.Length = 4;
			subValue6.Line = line71;
			element6.DefaultSubValue = subValue6;
			element6.Hotspot = hotspot15;
			legendEntry10.Background = background19;
			line72.Color = System.Drawing.Color.Empty;
			legendEntry10.DividerLine = line72;
			legendEntry10.Hotspot = hotspot16;
			element6.LegendEntry = legendEntry10;
			element6.XAxisTick = null;
			element6.YAxisTick = null;
			chartArea4.DefaultElement = element6;
			line73.Color = System.Drawing.Color.LightGray;
			chartArea4.InteriorLine = line73;
			label9.Font = new System.Drawing.Font("Tahoma", 8F);
			label9.Truncation = truncation13;
			chartArea4.Label = label9;
			chartArea4.LegendBox = null;
			line74.Color = System.Drawing.Color.Gray;
			chartArea4.Line = line74;
			chartArea4.Shadow = shadow11;
			chartArea4.StartDateOfYear = new System.DateTime(((long)(0)));
			background20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box4.Background = background20;
			line75.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box4.InteriorLine = line75;
			label10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label10.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label10.Truncation = truncation14;
			box4.Label = label10;
			line76.Color = System.Drawing.Color.Gray;
			box4.Line = line76;
			box4.Shadow = shadow12;
			box4.Visible = true;
			chartArea4.TitleBox = box4;
			chartArea4.XAxis = axis4;
			this.chartActiveSensors.VolumeArea = chartArea4;
			// 
			// gbNetwork
			// 
			this.gbNetwork.Controls.Add(this.SensorTopView);
			this.gbNetwork.Location = new System.Drawing.Point(3, 275);
			this.gbNetwork.Name = "gbNetwork";
			this.gbNetwork.Size = new System.Drawing.Size(852, 584);
			this.gbNetwork.TabIndex = 2;
			this.gbNetwork.TabStop = false;
			this.gbNetwork.Text = "Top View of The Network";
			// 
			// SensorTopView
			// 
			this.SensorTopView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SensorTopView.BackgroundImage")));
			this.SensorTopView.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.SensorTopView.Location = new System.Drawing.Point(72, 12);
			this.SensorTopView.Name = "SensorTopView";
			this.SensorTopView.Size = new System.Drawing.Size(692, 570);
			this.SensorTopView.TabIndex = 0;
			this.SensorTopView.TabStop = false;
			// 
			// buttonDemo
			// 
			this.buttonDemo.Location = new System.Drawing.Point(126, 862);
			this.buttonDemo.Name = "buttonDemo";
			this.buttonDemo.Size = new System.Drawing.Size(75, 23);
			this.buttonDemo.TabIndex = 3;
			this.buttonDemo.Text = "Demo";
			this.buttonDemo.UseVisualStyleBackColor = true;
			this.buttonDemo.Click += new System.EventHandler(this.buttonDemo_Click);
			// 
			// buttonClose
			// 
			this.buttonClose.Location = new System.Drawing.Point(637, 862);
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.Size = new System.Drawing.Size(75, 23);
			this.buttonClose.TabIndex = 4;
			this.buttonClose.Text = "Close";
			this.buttonClose.UseVisualStyleBackColor = true;
			this.buttonClose.Click += new System.EventHandler(this.buttonClose_Click);
			// 
			// tcCharts
			// 
			this.tcCharts.Controls.Add(this.tabPageData);
			this.tcCharts.Controls.Add(this.tabPagePerformance);
			this.tcCharts.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.tcCharts.Location = new System.Drawing.Point(0, 12);
			this.tcCharts.Multiline = true;
			this.tcCharts.Name = "tcCharts";
			this.tcCharts.SelectedIndex = 0;
			this.tcCharts.Size = new System.Drawing.Size(866, 923);
			this.tcCharts.TabIndex = 5;
			// 
			// tabPageData
			// 
			this.tabPageData.BackColor = System.Drawing.Color.White;
			this.tabPageData.Controls.Add(this.buttonClear);
			this.tabPageData.Controls.Add(this.buttonClose);
			this.tabPageData.Controls.Add(this.gbActiveSensors);
			this.tabPageData.Controls.Add(this.gbPrecision);
			this.tabPageData.Controls.Add(this.buttonDemo);
			this.tabPageData.Controls.Add(this.gbNetwork);
			this.tabPageData.Location = new System.Drawing.Point(4, 22);
			this.tabPageData.Name = "tabPageData";
			this.tabPageData.Padding = new System.Windows.Forms.Padding(3);
			this.tabPageData.Size = new System.Drawing.Size(858, 897);
			this.tabPageData.TabIndex = 0;
			this.tabPageData.Text = "Data";
			this.tabPageData.UseVisualStyleBackColor = true;
			// 
			// tabPagePerformance
			// 
			this.tabPagePerformance.BackColor = System.Drawing.Color.White;
			this.tabPagePerformance.Controls.Add(this.buttonReset);
			this.tabPagePerformance.Controls.Add(this.button1);
			this.tabPagePerformance.Controls.Add(this.groupBox2);
			this.tabPagePerformance.Controls.Add(this.groupBox1);
			this.tabPagePerformance.Location = new System.Drawing.Point(4, 22);
			this.tabPagePerformance.Name = "tabPagePerformance";
			this.tabPagePerformance.Padding = new System.Windows.Forms.Padding(3);
			this.tabPagePerformance.Size = new System.Drawing.Size(858, 799);
			this.tabPagePerformance.TabIndex = 1;
			this.tabPagePerformance.Text = "Performance";
			this.tabPagePerformance.UseVisualStyleBackColor = true;
			// 
			// buttonReset
			// 
			this.buttonReset.Location = new System.Drawing.Point(532, 761);
			this.buttonReset.Name = "buttonReset";
			this.buttonReset.Size = new System.Drawing.Size(75, 23);
			this.buttonReset.TabIndex = 5;
			this.buttonReset.Text = "Reset";
			this.buttonReset.UseVisualStyleBackColor = true;
			this.buttonReset.Click += new System.EventHandler(this.buttonReset_Click);
			// 
			// button1
			// 
			this.button1.Location = new System.Drawing.Point(364, 761);
			this.button1.Name = "button1";
			this.button1.Size = new System.Drawing.Size(75, 23);
			this.button1.TabIndex = 4;
			this.button1.Text = "Demo";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new System.EventHandler(this.button1_Click);
			// 
			// groupBox2
			// 
			this.groupBox2.Controls.Add(this.chartCumulative);
			this.groupBox2.Location = new System.Drawing.Point(6, 460);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(843, 295);
			this.groupBox2.TabIndex = 3;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Cumulative Success Rate";
			// 
			// chartCumulative
			// 
			this.chartCumulative.Application = "";
            //this.chartCumulative.ApplicationDNC = "";
			this.chartCumulative.Background.Color = System.Drawing.Color.White;
			background21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea5.Background = background21;
			line77.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			subValue7.Line = line77;
			element7.DefaultSubValue = subValue7;
			element7.Hotspot = hotspot17;
			legendEntry11.Background = background22;
			line78.Color = System.Drawing.Color.Empty;
			legendEntry11.DividerLine = line78;
			legendEntry11.Hotspot = hotspot18;
			element7.LegendEntry = legendEntry11;
			element7.XAxisTick = null;
			element7.YAxisTick = null;
			chartArea5.DefaultElement = element7;
			line79.Color = System.Drawing.Color.LightGray;
			chartArea5.InteriorLine = line79;
			label11.Font = new System.Drawing.Font("Tahoma", 8F);
			label11.Truncation = truncation15;
			chartArea5.Label = label11;
			background23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			legendBox3.Background = background23;
			legendBox3.CornerBottomRight = dotnetCHARTING.WinForms.BoxCorner.Cut;
			legendEntry12.Background = background24;
			line80.Color = System.Drawing.Color.Empty;
			legendEntry12.DividerLine = line80;
			legendEntry12.Hotspot = hotspot19;
			label12.Truncation = truncation16;
			legendEntry12.LabelStyle = label12;
			legendBox3.DefaultEntry = legendEntry12;
			legendEntry13.Background = background25;
			line81.Color = System.Drawing.Color.Gray;
			legendEntry13.DividerLine = line81;
			legendEntry13.Hotspot = hotspot20;
			legendEntry13.Name = "Name";
			legendEntry13.SortOrder = -1;
			legendEntry13.Value = "Value";
			legendEntry13.Visible = false;
			legendBox3.HeaderEntry = legendEntry13;
			line82.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			legendBox3.InteriorLine = line82;
			legendBox3.LabelStyle = label12;
			line83.Color = System.Drawing.Color.Gray;
			legendBox3.Line = line83;
			legendBox3.Padding = 4;
			legendBox3.Shadow = shadow13;
			legendBox3.Visible = true;
			chartArea5.LegendBox = legendBox3;
			line84.Color = System.Drawing.Color.Gray;
			chartArea5.Line = line84;
			chartArea5.Shadow = shadow14;
			chartArea5.StartDateOfYear = new System.DateTime(((long)(0)));
			background26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box5.Background = background26;
			line85.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box5.InteriorLine = line85;
			label13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label13.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label13.Truncation = truncation17;
			box5.Label = label13;
			line86.Color = System.Drawing.Color.Gray;
			box5.Line = line86;
			box5.Position = null;
			box5.Shadow = shadow15;
			box5.Visible = true;
			chartArea5.TitleBox = box5;
			this.chartCumulative.ChartArea = chartArea5;
			this.chartCumulative.DataGrid = null;
			axis7.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line87.Color = System.Drawing.Color.LightGray;
			axisTick17.GridLine = line87;
			line88.Length = 3;
			axisTick17.Line = line88;
			axisTick17.ValueLow = double.NaN;
			axis7.DefaultTick = axisTick17;
			axis7.LabelMarker = null;
			axis7.LogarithmicBase = 10;
			axis7.OverlappingCircularLabelSeparator = " & ";
			axis7.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis7.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange7.ValueLow = double.NaN;
			axis7.ScaleRange = scaleRange7;
			axis7.TickLabelAngle = 45F;
			axis7.TickLabelSeparatorLine = line89;
			line90.Color = System.Drawing.Color.Red;
			axisTick18.GridLine = line90;
			line91.Length = 3;
			axisTick18.Line = line91;
			axisTick18.ValueLow = double.NaN;
			axis7.ZeroTick = axisTick18;
			this.chartCumulative.DefaultAxis = axis7;
			this.chartCumulative.DefaultCultureName = "";
			line92.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			subValue8.Line = line92;
			element8.DefaultSubValue = subValue8;
			element8.Hotspot = hotspot21;
			legendEntry14.Background = background27;
			line93.Color = System.Drawing.Color.Empty;
			legendEntry14.DividerLine = line93;
			legendEntry14.Hotspot = hotspot22;
			element8.LegendEntry = legendEntry14;
			smartLabel3.Color = System.Drawing.Color.Empty;
			smartLabel3.Line = line94;
			smartLabel3.Truncation = truncation18;
			element8.SmartLabel = smartLabel3;
			element8.XAxisTick = null;
			element8.YAxisTick = null;
			this.chartCumulative.DefaultElement = element8;
			this.chartCumulative.DefaultShadow = shadow16;
			this.chartCumulative.Dock = System.Windows.Forms.DockStyle.Fill;
			this.chartCumulative.Location = new System.Drawing.Point(3, 16);
			this.chartCumulative.Name = "chartCumulative";
			this.chartCumulative.NoDataLabel.Text = "No Data";
			this.chartCumulative.NoDataLabel.Truncation = truncation19;
			this.chartCumulative.Size = new System.Drawing.Size(837, 276);
			this.chartCumulative.SmartLabelLine = line94;
			this.chartCumulative.SmartPaletteAutoSync = false;
			this.chartCumulative.StartDateOfYear = new System.DateTime(((long)(0)));
			this.chartCumulative.TabIndex = 0;
			this.chartCumulative.TempDirectory = "C:\\Documents and Settings\\Cihan\\Local Settings\\Temp\\";
			this.chartCumulative.ToolTipTemplate = "";
			background28.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea6.Background = background28;
			subValue9.Line = line95;
			element9.DefaultSubValue = subValue9;
			element9.Hotspot = hotspot23;
			legendEntry15.Background = background29;
			line96.Color = System.Drawing.Color.Empty;
			legendEntry15.DividerLine = line96;
			legendEntry15.Hotspot = hotspot24;
			element9.LegendEntry = legendEntry15;
			element9.XAxisTick = null;
			element9.YAxisTick = null;
			chartArea6.DefaultElement = element9;
			line97.Color = System.Drawing.Color.LightGray;
			chartArea6.InteriorLine = line97;
			label14.Font = new System.Drawing.Font("Tahoma", 8F);
			label14.Truncation = truncation20;
			chartArea6.Label = label14;
			chartArea6.LegendBox = null;
			line98.Color = System.Drawing.Color.Gray;
			chartArea6.Line = line98;
			chartArea6.Shadow = shadow17;
			chartArea6.StartDateOfYear = new System.DateTime(((long)(0)));
			background30.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box6.Background = background30;
			line99.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box6.InteriorLine = line99;
			label15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label15.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label15.Truncation = truncation21;
			box6.Label = label15;
			line100.Color = System.Drawing.Color.Gray;
			box6.Line = line100;
			box6.Position = null;
			box6.Shadow = shadow18;
			box6.Visible = true;
			chartArea6.TitleBox = box6;
			this.chartCumulative.VolumeArea = chartArea6;
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.chartGauges);
			this.groupBox1.Location = new System.Drawing.Point(3, 6);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(849, 448);
			this.groupBox1.TabIndex = 2;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Packet Success Rate";
			// 
			// chartGauges
			// 
			this.chartGauges.Application = "";
            //this.chartGauges.ApplicationDNC = "";
			this.chartGauges.Background.Color = System.Drawing.Color.White;
			background31.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea7.Background = background31;
			line101.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			subValue10.Line = line101;
			element10.DefaultSubValue = subValue10;
			element10.Hotspot = hotspot25;
			legendEntry16.Background = background32;
			line102.Color = System.Drawing.Color.Empty;
			legendEntry16.DividerLine = line102;
			legendEntry16.Hotspot = hotspot26;
			element10.LegendEntry = legendEntry16;
			element10.XAxisTick = null;
			element10.YAxisTick = null;
			chartArea7.DefaultElement = element10;
			line103.Color = System.Drawing.Color.LightGray;
			chartArea7.InteriorLine = line103;
			label16.Font = new System.Drawing.Font("Tahoma", 8F);
			label16.Truncation = truncation22;
			chartArea7.Label = label16;
			background33.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			legendBox4.Background = background33;
			legendBox4.CornerBottomRight = dotnetCHARTING.WinForms.BoxCorner.Cut;
			legendEntry17.Background = background34;
			line104.Color = System.Drawing.Color.Empty;
			legendEntry17.DividerLine = line104;
			legendEntry17.Hotspot = hotspot27;
			label17.Truncation = truncation23;
			legendEntry17.LabelStyle = label17;
			legendBox4.DefaultEntry = legendEntry17;
			legendEntry18.Background = background35;
			line105.Color = System.Drawing.Color.Gray;
			legendEntry18.DividerLine = line105;
			legendEntry18.Hotspot = hotspot28;
			legendEntry18.Name = "Name";
			legendEntry18.SortOrder = -1;
			legendEntry18.Value = "Value";
			legendEntry18.Visible = false;
			legendBox4.HeaderEntry = legendEntry18;
			line106.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			legendBox4.InteriorLine = line106;
			legendBox4.LabelStyle = label17;
			line107.Color = System.Drawing.Color.Gray;
			legendBox4.Line = line107;
			legendBox4.Padding = 4;
			legendBox4.Shadow = shadow19;
			legendBox4.Visible = true;
			chartArea7.LegendBox = legendBox4;
			line108.Color = System.Drawing.Color.Gray;
			chartArea7.Line = line108;
			chartArea7.Shadow = shadow20;
			chartArea7.StartDateOfYear = new System.DateTime(((long)(0)));
			background36.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box7.Background = background36;
			line109.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box7.InteriorLine = line109;
			label18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label18.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label18.Truncation = truncation24;
			box7.Label = label18;
			line110.Color = System.Drawing.Color.Gray;
			box7.Line = line110;
			box7.Position = null;
			box7.Shadow = shadow21;
			box7.Visible = true;
			chartArea7.TitleBox = box7;
			this.chartGauges.ChartArea = chartArea7;
			this.chartGauges.DataGrid = null;
			axis8.CombinedElementsCalculation = dotnetCHARTING.WinForms.Calculation.Sum;
			line111.Color = System.Drawing.Color.LightGray;
			axisTick19.GridLine = line111;
			line112.Length = 3;
			axisTick19.Line = line112;
			axisTick19.ValueLow = double.NaN;
			axis8.DefaultTick = axisTick19;
			axis8.LabelMarker = null;
			axis8.LogarithmicBase = 10;
			axis8.OverlappingCircularLabelSeparator = " & ";
			axis8.RadarMode = dotnetCHARTING.WinForms.RadarMode.Spider;
			axis8.ScaleBreakStyle = dotnetCHARTING.WinForms.ScaleBreakStyle.ZigZag;
			scaleRange8.ValueLow = double.NaN;
			axis8.ScaleRange = scaleRange8;
			axis8.TickLabelAngle = 45F;
			axis8.TickLabelSeparatorLine = line113;
			line114.Color = System.Drawing.Color.Red;
			axisTick20.GridLine = line114;
			line115.Length = 3;
			axisTick20.Line = line115;
			axisTick20.ValueLow = double.NaN;
			axis8.ZeroTick = axisTick20;
			this.chartGauges.DefaultAxis = axis8;
			this.chartGauges.DefaultCultureName = "";
			line116.Color = System.Drawing.Color.FromArgb(((int)(((byte)(93)))), ((int)(((byte)(28)))), ((int)(((byte)(59)))));
			subValue11.Line = line116;
			element11.DefaultSubValue = subValue11;
			element11.Hotspot = hotspot29;
			legendEntry19.Background = background37;
			line117.Color = System.Drawing.Color.Empty;
			legendEntry19.DividerLine = line117;
			legendEntry19.Hotspot = hotspot30;
			element11.LegendEntry = legendEntry19;
			smartLabel4.Color = System.Drawing.Color.Empty;
			smartLabel4.Line = line118;
			smartLabel4.Truncation = truncation25;
			element11.SmartLabel = smartLabel4;
			element11.XAxisTick = null;
			element11.YAxisTick = null;
			this.chartGauges.DefaultElement = element11;
			this.chartGauges.DefaultShadow = shadow22;
			this.chartGauges.Dock = System.Windows.Forms.DockStyle.Fill;
			this.chartGauges.Location = new System.Drawing.Point(3, 16);
			this.chartGauges.Name = "chartGauges";
			this.chartGauges.NoDataLabel.Text = "No Data";
			this.chartGauges.NoDataLabel.Truncation = truncation26;
			this.chartGauges.Size = new System.Drawing.Size(843, 429);
			this.chartGauges.SmartLabelLine = line118;
			this.chartGauges.SmartPaletteAutoSync = false;
			this.chartGauges.StartDateOfYear = new System.DateTime(((long)(0)));
			this.chartGauges.TabIndex = 0;
			this.chartGauges.TempDirectory = "C:\\Documents and Settings\\Cihan\\Local Settings\\Temp\\";
			this.chartGauges.ToolTipTemplate = "";
			background38.Color = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(235)))), ((int)(((byte)(238)))));
			chartArea8.Background = background38;
			subValue12.Line = line119;
			element12.DefaultSubValue = subValue12;
			element12.Hotspot = hotspot31;
			legendEntry20.Background = background39;
			line120.Color = System.Drawing.Color.Empty;
			legendEntry20.DividerLine = line120;
			legendEntry20.Hotspot = hotspot32;
			element12.LegendEntry = legendEntry20;
			element12.XAxisTick = null;
			element12.YAxisTick = null;
			chartArea8.DefaultElement = element12;
			line121.Color = System.Drawing.Color.LightGray;
			chartArea8.InteriorLine = line121;
			label19.Font = new System.Drawing.Font("Tahoma", 8F);
			label19.Truncation = truncation27;
			chartArea8.Label = label19;
			chartArea8.LegendBox = null;
			line122.Color = System.Drawing.Color.Gray;
			chartArea8.Line = line122;
			chartArea8.Shadow = shadow23;
			chartArea8.StartDateOfYear = new System.DateTime(((long)(0)));
			background40.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(219)))));
			box8.Background = background40;
			line123.Color = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			box8.InteriorLine = line123;
			label20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(45)))), ((int)(((byte)(38)))));
			label20.Font = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold);
			label20.Truncation = truncation28;
			box8.Label = label20;
			line124.Color = System.Drawing.Color.Gray;
			box8.Line = line124;
			box8.Position = null;
			box8.Shadow = shadow24;
			box8.Visible = true;
			chartArea8.TitleBox = box8;
			this.chartGauges.VolumeArea = chartArea8;
			// 
			// buttonClear
			// 
			this.buttonClear.Location = new System.Drawing.Point(386, 862);
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.Size = new System.Drawing.Size(75, 23);
			this.buttonClear.TabIndex = 5;
			this.buttonClear.Text = "Clear";
			this.buttonClear.UseVisualStyleBackColor = true;
			this.buttonClear.Click += new System.EventHandler(this.buttonClear_Click);
			// 
			// DSNPerformanceForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.White;
			this.ClientSize = new System.Drawing.Size(865, 935);
			this.Controls.Add(this.tcCharts);
			this.Name = "DSNPerformanceForm";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Network View";
			this.gbPrecision.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chartPrecision)).EndInit();
			this.gbActiveSensors.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chartActiveSensors)).EndInit();
			this.gbNetwork.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.SensorTopView)).EndInit();
			this.tcCharts.ResumeLayout(false);
			this.tabPageData.ResumeLayout(false);
			this.tabPagePerformance.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chartCumulative)).EndInit();
			this.groupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.chartGauges)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.GroupBox gbPrecision;
		private System.Windows.Forms.GroupBox gbActiveSensors;
		private System.Windows.Forms.GroupBox gbNetwork;
		private dotnetCHARTING.WinForms.Chart chartPrecision;
		private dotnetCHARTING.WinForms.Chart chartActiveSensors;
		private System.Windows.Forms.Button buttonDemo;
		private System.Windows.Forms.Button buttonClose;
		private System.Windows.Forms.TabControl tcCharts;
		private System.Windows.Forms.TabPage tabPageData;
		private System.Windows.Forms.TabPage tabPagePerformance;
		private System.Windows.Forms.Button button1;
		private System.Windows.Forms.GroupBox groupBox2;
		private dotnetCHARTING.WinForms.Chart chartCumulative;
		private System.Windows.Forms.GroupBox groupBox1;
		private dotnetCHARTING.WinForms.Chart chartGauges;
		private System.Windows.Forms.Button buttonReset;
        private System.Windows.Forms.PictureBox SensorTopView;
		private System.Windows.Forms.Button buttonClear;
	}
}